
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author amol
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Phone = new javax.swing.JPanel();
        insert = new javax.swing.JButton();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Exit = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        show = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(400, 160));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Phone.setBackground(new java.awt.Color(255, 102, 102));
        Phone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        insert.setText("Insert");
        insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertActionPerformed(evt);
            }
        });
        Phone.add(insert, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 100, 30));

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        Phone.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 100, 30));

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        Phone.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 100, 30));
        Phone.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 160, -1));
        Phone.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 70, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        Phone.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));
        Phone.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 160, -1));

        jLabel1.setText("Name");
        Phone.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jLabel2.setText("Gender");
        Phone.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setText("Age");
        Phone.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setText("Phone");
        Phone.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        Phone.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, 90, 30));

        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Phone.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 100, 30));

        getContentPane().add(Phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 500));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "null"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.getTableHeader().setReorderingAllowed(false);
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 410, 410));

        show.setText("Refresh");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        getContentPane().add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 80, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

          
    
    
    private void insertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertActionPerformed
        // TODO add your handling code here:
             String Gender = (String) jComboBox1.getSelectedItem();        
             String Name = jTextField1.getText();
             String Phone = jTextField3.getText();
             
            
            if(Name.isEmpty() || Phone.isEmpty() || jTextField2.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this,"Empty field");            
            }else{
                int Age = Integer.parseInt(jTextField2.getText()); 
                try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
                 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crud","root","oooo9999");
            
                 Statement st = con.createStatement();            
                 String Insert = "INSERT INTO details (name, gender, age, phone) VALUES('"+Name+"','"+Gender+"',"+Age+",'"+Phone+"')";
                 st.executeUpdate(Insert);
                 JOptionPane.showMessageDialog(this, "Successfully added");          
            
                }
                 catch(HeadlessException | ClassNotFoundException | SQLException e){
                 JOptionPane.showMessageDialog(this, e.toString());
                }
            }
    }//GEN-LAST:event_insertActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crud","root","oooo9999");
            
            Statement st = con.createStatement();            
            
            ResultSet rs = st.executeQuery("select * from details");
            table.setModel(DbUtils.resultSetToTableModel(rs));
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }//GEN-LAST:event_showActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
      
       
        int a = JOptionPane.showConfirmDialog(this, "Are you sure?");
        if(a==JOptionPane.YES_OPTION){
             setVisible(false);
             new Login().setVisible(true);
        }
    }//GEN-LAST:event_ExitActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
       
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crud","root","oooo9999");
            
            Statement st = con.createStatement();            
            
            ResultSet rs = st.executeQuery("select * from details");
            table.setModel(DbUtils.resultSetToTableModel(rs));
             
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, e.toString());
        }
        
    }//GEN-LAST:event_formComponentShown

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
         
         if(table.getSelectedRowCount()>1) return;            
         
             String Gender = (String) jComboBox1.getSelectedItem();        
             String Name = jTextField1.getText();
             String Phone = jTextField3.getText();
              int Age = Integer.parseInt(jTextField2.getText()); 
           
             int key = 1;
       if(Name.isEmpty() || Phone.isEmpty() || jTextField2.getText().isEmpty()){
                    JOptionPane.showMessageDialog(this,"Empty field");            
        }else{    
             
              
            try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
                 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crud","root","oooo9999");
            
                 Statement st = con.createStatement();            
                 String update = "UPDATE details SET name='"+Name+"', age="+Age+", gender='"+Gender+"', phone='"+Phone+"' WHERE id="+key+"";
                 st.executeUpdate(update);
                 JOptionPane.showMessageDialog(this, "Successfully updated");          
            
             }
             catch(HeadlessException | ClassNotFoundException | SQLException e){
                 JOptionPane.showMessageDialog(this, e.toString());
             }
       }
    }//GEN-LAST:event_updateActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
       DefaultTableModel tbModel = (DefaultTableModel) table.getModel();
       String tbName = tbModel.getValueAt(table.getSelectedRow(), 1).toString();
       Object tbGender = (Object) tbModel.getValueAt(table.getSelectedRow(), 2);
       String tbAge = tbModel.getValueAt(table.getSelectedRow(), 3).toString();      
       String tbPhone = tbModel.getValueAt(table.getSelectedRow(), 4).toString();
        
             jComboBox1.setSelectedItem(tbGender);
             jTextField1.setText(tbName);
              jTextField3.setText(tbPhone);
              jTextField2.setText(tbAge); 
    }//GEN-LAST:event_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
            jComboBox1.setSelectedItem(null);
             jTextField1.setText("");
              jTextField3.setText("");
              jTextField2.setText(""); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
         DefaultTableModel tbModel = (DefaultTableModel) table.getModel();
          String tbName = tbModel.getValueAt(table.getSelectedRow(), 1).toString();
       String tbGender = tbModel.getValueAt(table.getSelectedRow(), 2).toString();
       String s = tbModel.getValueAt(table.getSelectedRow(), 3).toString();      
       int tbAge = Integer.parseInt(s);
       String tbPhone = tbModel.getValueAt(table.getSelectedRow(), 4).toString();
        if(table.getSelectedRowCount()==1){
            try{
                 Class.forName("com.mysql.cj.jdbc.Driver");
                 Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/crud","root","oooo9999");
            
                 Statement st = con.createStatement();            
                 String delete = "Delete FROM details WHERE name='"+tbName+"' and age="+tbAge+" and gender='"+tbGender+"' and phone='"+tbPhone+"'";
                 st.executeUpdate(delete);
                 JOptionPane.showMessageDialog(this, "Successfully deleted");          
            
             }
             catch(HeadlessException | ClassNotFoundException | SQLException e){
                 JOptionPane.showMessageDialog(this, e.toString());
             }
        }
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit;
    private javax.swing.JPanel Phone;
    private javax.swing.JButton delete;
    private javax.swing.JButton insert;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JButton show;
    private javax.swing.JTable table;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
